[package]
name = "backend"
version = "0.1.0"
edition = "2021"

[dependencies]
sqlx = { version = "0.8.6", features = [
    "sqlite",
    "runtime-async-std-native-tls",
] }
async-std = { version = "1.13.1", features = ["attributes"] }
futures = "0.3.31"
